apiVersion: v1
kind: Secret
metadata:
  name: dynatrace-secret
  namespace: flagger-system
type: Opaque
data:
  api-token: # base64 encoded Dynatrace API token
---
apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: dynatrace-success-rate
  namespace: flagger-system
spec:
  provider:
    type: dynatrace
    address: https://{{ args.environment }}.live.dynatrace.com
    secretRef:
      name: dynatrace-secret
      key: api-token
  query: |
    builtin:service.errors.server.rate:splitBy("dt.entity.service"):filter(eq("dt.entity.service","{{ args.name }}")):avg
  thresholds:
    - name: success-rate
      min: 95
      max: 100
---
apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: dynatrace-latency
  namespace: flagger-system
spec:
  provider:
    type: dynatrace
    address: https://{{ args.environment }}.live.dynatrace.com
    secretRef:
      name: dynatrace-secret
      key: api-token
  query: |
    builtin:service.response.time:splitBy("dt.entity.service"):filter(eq("dt.entity.service","{{ args.name }}")):avg
  thresholds:
    - name: latency
      min: 0
      max: 500