apiVersion: v1
kind: Secret
metadata:
  name: honeycomb-otel-secret
  namespace: flagger-system
type: Opaque
data:
  # INGEST KEY: Used by OpenTelemetry Collector to send traces/metrics to Honeycomb
  # Format: hcaik_* (Honeycomb API Ingest Key)
  api-key: # base64 encoded Honeycomb INGEST API key - set this when you have a key
stringData:
  # Uncomment and set your actual Honeycomb INGEST API key here
  # api-key: "hcaik_your-ingest-key-here"
---
apiVersion: v1
kind: Secret
metadata:
  name: honeycomb-query-secret
  namespace: flagger-system
type: Opaque
data:
  # QUERY KEY: Used by Honeycomb Adapter to read data from Honeycomb for Flagger
  # Format: hcqk_* (Honeycomb Query Key) - different from ingest key!
  api-key: # base64 encoded Honeycomb QUERY API key - set this when you have a key
stringData:
  # Uncomment and set your actual Honeycomb QUERY API key here
  # api-key: "hcqk_your-query-key-here"