apiVersion: v1
kind: Secret
metadata:
  name: honeycomb-otel-secret
  namespace: flagger-system
type: Opaque
data:
  api-key: # base64 encoded Honeycomb API key - set this when you have a key
stringData:
  # Uncomment and set your actual Honeycomb API key here
  # api-key: "your-honeycomb-api-key-here"