apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
  namespace: flagger-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-collector
subjects:
  - kind: ServiceAccount
    name: otel-collector
    namespace: flagger-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: flagger-system
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      serviceAccountName: otel-collector
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:latest
          args:
            - "--config=/etc/otel-collector-config/config.yaml"
          env:
            - name: HONEYCOMB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: honeycomb-otel-secret
                  key: api-key
                  optional: true
          ports:
            - containerPort: 13133 # Health check
              name: health
            - containerPort: 1777  # pprof
              name: pprof
            - containerPort: 55679 # zpages
              name: zpages
          volumeMounts:
            - name: otel-collector-config
              mountPath: /etc/otel-collector-config
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: otel-collector-config
          configMap:
            name: otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: flagger-system
  labels:
    app: otel-collector
spec:
  selector:
    app: otel-collector
  ports:
    - name: health
      port: 13133
      targetPort: 13133
    - name: pprof
      port: 1777
      targetPort: 1777
    - name: zpages
      port: 55679
      targetPort: 55679