apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otel-instrumentation
  namespace: test
spec:
  exporter:
    endpoint: http://otel-collector.flagger-system:4318
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: always_on
  resource:
    addK8sUIDAttributes: true
  # Auto-instrumentation for different languages
  go:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-go:v0.2.1-alpha
    env:
      - name: OTEL_SERVICE_NAME
        value: "podinfo"
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: "service.name=podinfo,service.version=6.0.0"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.32.0
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.46.0
  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.43b0
  dotnet:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:1.0.0-rc.2