apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: simple-success-rate
  namespace: flagger-system
spec:
  provider:
    type: prometheus
    address: http://prometheus.istio-system:9090
  query: |
    vector(100)
---
apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: simple-latency
  namespace: flagger-system
spec:
  provider:
    type: prometheus
    address: http://prometheus.istio-system:9090
  query: |
    vector(100)
---
apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: simple-request-rate
  namespace: flagger-system
spec:
  provider:
    type: prometheus
    address: http://prometheus.istio-system:9090
  query: |
    vector(10)