apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: podinfo-canary
  namespace: test
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
  progressDeadlineSeconds: 60
  service:
    port: 9898
  analysis:
    interval: 30s
    threshold: 3
    maxWeight: 50
    stepWeight: 10
    metrics:
    - name: simple-success-rate
      templateRef:
        name: simple-success-rate
        namespace: flagger-system
      thresholdRange:
        min: 95
      interval: 30s
    - name: simple-latency
      templateRef:
        name: simple-latency
        namespace: flagger-system  
      thresholdRange:
        max: 500
      interval: 30s
    - name: simple-request-rate
      templateRef:
        name: simple-request-rate
        namespace: flagger-system
      thresholdRange:
        min: 1
      interval: 30s
    webhooks:
    - name: load-test-get
      url: http://flagger-loadtester.test/
      timeout: 5s
      metadata:
        cmd: "hey -z 30s -q 10 -c 2 http://podinfo-canary.test:9898/"