apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: test
  labels:
    app: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
      annotations: {}
    spec:
      containers:
      - name: test-app
        image: ghcr.io/stefanprodan/podinfo:6.0.3
        ports:
        - containerPort: 9898
          name: http
        env:
        - name: PODINFO_UI_COLOR
          value: "#34577c"
        - name: OTEL_SERVICE_NAME
          value: "test-app"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=test-app,service.version=1.0.0"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.flagger-system:4318"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: test-app
  namespace: test
  labels:
    app: test-app
spec:
  type: ClusterIP
  ports:
  - port: 9898
    targetPort: 9898
    protocol: TCP
    name: http
  selector:
    app: test-app
