apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-otel-app
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-otel-app
  template:
    metadata:
      labels:
        app: test-otel-app
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: test-app
        image: otel/opentelemetry-demo-frontend:1.5.0
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "https://api.honeycomb.io"
        - name: OTEL_EXPORTER_OTLP_HEADERS
          value: "x-honeycomb-team=hcaik_01j2kngfkxvj3tr6q3k4p3cgm1dj8t5qd0fq1qxm4pz3xqczpm5v9r,x-honeycomb-dataset=podinfo-service"
        - name: OTEL_SERVICE_NAME
          value: "test-otel-app"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=test-otel-app,service.version=1.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: test-otel-app
  namespace: test
spec:
  selector:
    app: test-otel-app
  ports:
  - port: 8080
    targetPort: 8080