apiVersion: v1
kind: Secret
metadata:
  name: honeycomb-secret
  namespace: flagger-system
type: Opaque
data:
  # Base64 encoded Honeycomb API key
  # Replace with: echo -n "your-honeycomb-api-key" | base64
  api-key: # YOUR_BASE64_ENCODED_API_KEY
---
# Alternative: Create secret imperatively
# kubectl create secret generic honeycomb-secret \
#   --from-literal=api-key=YOUR_HONEYCOMB_API_KEY \
#   --namespace=flagger-system