apiVersion: v1
kind: Secret
metadata:
  name: honeycomb-query-secret
  namespace: flagger-system
type: Opaque
data:
  # Base64 encoded Honeycomb QUERY API key (not ingestion key)
  # Replace with: echo -n "your-honeycomb-query-key" | base64
  api-key: # YOUR_BASE64_ENCODED_QUERY_KEY
---
# Alternative: Create secret imperatively
# kubectl create secret generic honeycomb-query-secret \
#   --from-literal=api-key=YOUR_HONEYCOMB_QUERY_KEY \
#   --namespace=flagger-system