apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: honeycomb-adapter
  name: honeycomb-adapter
  namespace: flagger-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: honeycomb-adapter
  template:
    metadata:
      labels:
        app: honeycomb-adapter
    spec:
      containers:
      - image: honeycomb-adapter:latest
        name: honeycomb-adapter
        ports:
        - containerPort: 9090
        env:
        - name: HONEYCOMB_API_KEY
          valueFrom:
            secretKeyRef:
              name: honeycomb-query-secret
              key: api-key
        - name: LOG_LEVEL
          value: "debug"
        imagePullPolicy: Never
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi" 
            cpu: "100m"
